### ISSUE TITLE
GraphQL schema file

### ISSUE THREAD

**Issue by jdmills-edu** [screencloud/developer#109]
Hi ScreenCloud team,

I'm working on an integration between our emergency alert system (Omnilert) and ScreenCloud. It would be helpful if I could import a GraphQL schema file into Postman or similar for further exploration. I've searched and cannot find such a file. Is one readily available, and if not, would you consider publishing one?

Thanks!

JD Mills
Davidson College

**Comment by michael-martin** [comment]
@jdmills-edu Sorry for the super slow reply here, have only seen this today! 🙈 

Sure thing; you can inspect the full GraphQL schema by hitting the `/graphql` endpoint itself, e.g. if you're on a US Studio account, full address is: `https://graphql.us.screencloud.com/graphql`

The one thing you need to do first is to provide your token, can see how to do that here: https://screencloud.github.io/signage-next-graphql-docs/get-an-api-token

You might find it easier to use a dedicated GraphQL client rather than Postman, at least for building up the queries, e.g. https://altair.sirmuel.design/ is a good free one

The nice thing it will do is put all of that schema info in a nice searchable format in the sidebar while you build your queries.

This guide explains how you can use Altair to fetch a schema file for Postman like you described if you prefer to stay totally within Postman: https://qatechtools.com/2020/05/27/how-to-import-graphql-schema-and-use-auto-complete-feature-and-in-postman/ (only catch is you may want to periodically update that file)

**Comment by jdmills-edu** [comment]
This is super helpful, thank you so much!
